CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE TENANT (
    ID UUID DEFAULT uuid_generate_v4(),
    NAME VARCHAR NOT NULL,
    DOMAIN VARCHAR NOT NULL,
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);