CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE TENANT (
    ID UUID DEFAULT uuid_generate_v4(),
    NAME VARCHAR NOT NULL UNIQUE,
    URL VARCHAR NOT NULL UNIQUE,
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);