version: "3.3"
services:
  app:
    build:
      context: .
    container_name: brewcraftapp
    entrypoint: ["/bin/bash", "-c"]
    command: ["./wait-for-it.sh --strict --timeout=20 localstack:4566 && java -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=*:8000 -jar brewcraftapp.jar"]
    ports:
      - 9010:9010
      - 8000:8000
    volumes:
      - ./wait-for-it.sh:/opt/app/wait-for-it.sh
    depends_on:
      - localstack
      - postgresdb

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "9001:${LS_WEB_UI}"
      - "4566-4599:4566-4599"
    environment:
      DEFAULT_REGION: ${AWS_REGION}
      HOSTNAME_EXTERNAL: ${AWS_HOSTNAME_EXTERNAL}
      USE_SSL: "false"
      PORT_WEB_UI: ${LS_WEB_UI}
      SERVICES: secretsmanager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  postgresdb:
    image: postgres
    restart: always
    volumes:
      - ./db-init-scripts:/docker-entrypoint-initdb.d
    container_name: brewcraft_postgresdb
    ports:
      - "54321:${POSTGRES_PORT}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      BREWCRAFT_MASTER_USER: ${BREWCRAFT_MASTER_USER}
      BREWCRAFT_MASTER_USER_PASSWORD: ${BREWCRAFT_MASTER_USER_PASSWORD}

  pg-admin:
    image: dpage/pgadmin4
    restart: always
    depends_on: 
      - postgresdb
    volumes:
      - db-admin-data:/var/lib/pgadmin
    container_name: brewcraft_pgadmin
    ports:
        - "8443:443"
    logging:
        driver: none
    environment: 
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        PGADMIN_LISTEN_PORT: "443"

volumes:
  db-admin-data:
