version: "3.8"
services:
  app:
    build:
      context: .
    container_name: brewcraftapp
    ports:
      - "9000:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:${POSTGRES_PORT}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${BREWCRAFT_MASTER_USER}
      SPRING_DATASOURCE_PASSWORD: ${BREWCRAFT_MASTER_USER_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      JWT_ISSUER_URI: ${JWT_ISSUER_URI}
      JWK_SET_URI: ${JWK_SET_URI}
    depends_on:
      - localstack
      - postgresdb

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "9001:${LS_WEB_UI}"
      - "4566-4599:4566-4599"
    environment:
      DEFAULT_REGION: ${AWS_REGION}
      HOSTNAME_EXTERNAL: ${AWS_HOSTNAME_EXTERNAL}
      USE_SSL: "false"
      PORT_WEB_UI: ${LS_WEB_UI}
      SERVICES: secretsmanager
    volumes:
      - './.localstack:/tmp/localstack'
      - /var/run/docker.sock:/var/run/docker.sock

  postgresdb:
    image: postgres
    restart: always
    volumes:
      - ./db-init-scripts:/docker-entrypoint-initdb.d
    container_name: postgresdb
    ports:
      - "5432:${POSTGRES_PORT}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      BREWCRAFT_MASTER_USER: ${BREWCRAFT_MASTER_USER}
      BREWCRAFT_MASTER_USER_PASSWORD: ${BREWCRAFT_MASTER_USER_PASSWORD}

  pg-admin:
    image: dpage/pgadmin4
    restart: always
    depends_on: 
      - postgresdb
    volumes:
      - db-admin-data:/var/lib/pgadmin
    container_name: pgadmin
    ports:
        - "8443:443"
    logging:
        driver: none
    environment: 
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        PGADMIN_LISTEN_PORT: 443

volumes:
    db-admin-data: