version: "3.3"
services:
  app:
    image: brewcraft:${VERSION}
    container_name: brewcraftapp
    ports:
      - "9000:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:${POSTGRES_PORT}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${BREWCRAFT_MASTER_USER}
      SPRING_DATASOURCE_PASSWORD: ${BREWCRAFT_MASTER_USER_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      JWT_ISSUER_URI: ${JWT_ISSUER_URI}
      JWK_SET_URI: ${JWK_SET_URI}
