version: "3.3"
services:
  app:
    build:
      context: .
    container_name: brewcraftapp
    depends_on:
      - localstack
      - postgresdb

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "9001:${LS_WEB_UI}"
      - "4566-4599:4566-4599"
    environment:
      DEFAULT_REGION: ${AWS_REGION}
      HOSTNAME_EXTERNAL: ${AWS_HOSTNAME_EXTERNAL}
      USE_SSL: "false"
      PORT_WEB_UI: ${LS_WEB_UI}
      SERVICES: secretsmanager
      DATA_DIR: /tmp/localstack/data
    volumes:
      - localstack-data:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  postgresdb:
    image: postgres
    restart: always
    volumes:
      - ./db-init-scripts:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    container_name: postgresdb
    ports:
      - "54321:${POSTGRES_PORT}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      BREWCRAFT_MASTER_USER: ${BREWCRAFT_MASTER_USER}
      BREWCRAFT_MASTER_USER_PASSWORD: ${BREWCRAFT_MASTER_USER_PASSWORD}

  pg-admin:
    image: dpage/pgadmin4
    restart: always
    depends_on: 
      - postgresdb
    container_name: pgadmin
    ports:
        - "8443:443"
    logging:
        driver: none
    environment: 
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        PGADMIN_LISTEN_PORT: 443

volumes:
    db-admin-data:
    localstack-data: 