version: "3.3"
services:
  install:
    image: maven:3.6.3-jdk-11-openj9
    container_name: maven    
    working_dir: /usr/code/app
    command: ['mvn', 'clean', 'install']
    volumes:
      - ${PWD}:/usr/code/app
