version: "3.8"
services:
  app:
    build:
      context: .
    container_name: brewcraftapp
    ports:
      - "9000:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    depends_on:
      - localstack
      - postgresdb

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "9001:9001"
      - "4566-4599:4566-4599"
    environment:
      - DEFAULT_REGION=us-east-1
      - HOSTNAME_EXTERNAL=localstack
      - USE_SSL=false
      - PORT_WEB_UI=9001
      - DATA_DIR=/tmp/localstack/data
      - SERVICES=secretsmanager
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'

  postgresdb:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  pg-admin:
    image: dpage/pgadmin4
    restart: always
    volumes:
        - db-admin-data:/var/lib/pgadmin
    container_name: pgadmin
    ports:
        - "8443:443"
    logging:
        driver: none
    environment: 
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        PGADMIN_LISTEN_PORT: 443

volumes:
    db-data:
    db-admin-data: