version: "3.3"
services:
  install:
    image: maven:3.8.2-openjdk-17-slim
    container_name: brewcraft_maven
    working_dir: /usr/code/app
    command: ['mvn', 'clean', 'install']
    volumes:
      - ${PWD}:/usr/code/app
      - m2-data:/root/.m2
volumes:
  m2-data:
