apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: app-mt-provision-iam
data: 
  awsIamAccessKeyId: {{ .Values.multitenancy.provisioning.accessManagement.awsIam.accessKeyId | decryptAES (.Values.decryptKey) | b64enc }}
  awsIamAccessSecretKey: {{ .Values.multitenancy.provisioning.accessManagement.awsIam.accessSecretKey | decryptAES (.Values.decryptKey) | b64enc }}
