apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: brewcraft-backend
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.app.networking.ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path: /api
        backend:
          service:
            name: app-svc-http
            port:
              number: {{ .Values.app.networking.httpService.port }}
      - pathType: Prefix
        path: /actuator
        backend:
          service:
            name: app-svc-http
            port:
              number: {{ .Values.app.networking.httpService.port }}