env: development
replicaCount: 1

image:
  repository: docker.io/library
  pullPolicy: IfNotPresent

imagePullSecrets: []

resources:
  limits:
    cpu: 500m
    memory: 2G
  requests:
    cpu: 250m
    memory: 1.5G

app:
  networking:
    port:
      container: "8080"
      service: "8080"
  svc:
    type: NodePort
    nodePort: "31000"
