env: prod

image:
  repository: "782071516387.dkr.ecr.ca-central-1.amazonaws.com"
  pullPolicy: Always # TODO: Revert to ifNotPresent

imagePullSecrets: []

resources:
  limits:
    cpu: 500m
    memory: 2G
  requests:
    cpu: 250m
    memory: 1.5G

app:
  networking:
    port:
      container: "8080"
      service: "8080"
  svc:
    type: NodePort
    nodePort: "31000"


dependencies:
  postgresql:
    enabled: false
  pgadmin4:
    enabled: false
  localstack:
    enabled: false