CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE TEST (
    ID serial PRIMARY KEY,
    NAME VARCHAR NOT NULL,
    DOMAIN VARCHAR NOT NULL,
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);